const $ = id => document.getElementById(id);
const money = n => `KSh ${Number(n).toFixed(2)}`;
let currentExitPlate = '';
let currentExitFee = 0;
function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function showResult(el, html, ok=true){el.innerHTML=html;el.className=`result ${ok?'success':'error'}`}
async function api(url, options={}){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw data;return data}
async function refresh(){
  try{
    const s=await api('/api/status');
    $('totalSlots').textContent=s.totalSlots;$('availableSlots').textContent=s.availableSlots;$('occupiedSlots').textContent=s.occupiedSlots;$('revenue').textContent=money(s.revenue);$('vatCollected').textContent=money(s.vatCollected);
    $('slotGrid').innerHTML=s.slots.map(x=>`<div class="slot ${x.occupied?'occupied':'available'}"><b>Slot ${String(x.id).padStart(2,'0')}</b><small>${x.occupied?x.plate:'Available'}</small></div>`).join('');
    const t=await api('/api/transactions');
    $('transactionBody').innerHTML=t.transactions.length?t.transactions.slice().reverse().map(x=>`<tr><td>${esc(x.plate)}</td><td>${x.slot}</td><td>${esc(x.arrival)}</td><td>${esc(x.departure)}</td><td>${x.durationMinutes} min</td><td>${money(x.fee)}</td><td>${esc(x.paymentMethod||'-')}</td><td>${esc(x.paymentReference||'-')}</td><td>${esc(x.receiptNumber||'-')}</td><td>${money(x.vatAmount)}</td><td>${esc(x.paymentStatus)}</td></tr>`).join(''):`<tr><td colspan="11" class="empty">No completed transactions yet.</td></tr>`;
  }catch(e){toast(e.message||'Could not refresh the system.');}
}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
$('arrivalForm').addEventListener('submit',async e=>{e.preventDefault();const body=new URLSearchParams({plate:$('arrivalPlate').value,owner:$('owner').value});try{const r=await api('/api/arrival',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});toast(`Vehicle admitted to Slot ${String(r.slotId).padStart(2,'0')}`);e.target.reset();refresh()}catch(e){toast(e.message||'Arrival failed.')}});
 $('exitForm').addEventListener('submit',async e=>{e.preventDefault();const plate=$('exitPlate').value.trim();const body=new URLSearchParams({plate});try{const r=await api('/api/exit',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(r.fee===0){showResult($('exitResult'),`<b>Barrier OPEN</b><br>Duration: ${r.durationMinutes} minute(s)<br>Receipt: ${esc(r.receiptNumber)}`);$('paymentPanel').classList.add('hidden');currentExitPlate='';currentExitFee=0;e.target.reset();refresh()}else{currentExitPlate=plate;currentExitFee=r.fee;showResult($('exitResult'),`<b>Payment required</b><br>Duration: ${r.durationMinutes} minute(s)<br>Amount due: <b>${money(r.fee)}</b>`);$('paymentPanel').classList.remove('hidden');$('paymentReference').value='';$('paymentMethod').dispatchEvent(new Event('change'));$('paymentMethod').focus()}}catch(e){$('paymentPanel').classList.add('hidden');showResult($('exitResult'),e.message||'Exit calculation failed.',false)}});
$('paymentMethod').addEventListener('change',()=>{$('paymentReference').required=$('paymentMethod').value!=='CASH';$('referenceField').classList.toggle('hidden',$('paymentMethod').value==='CASH')});
$('paymentMethod').dispatchEvent(new Event('change'));
$('paymentForm').addEventListener('submit',async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;const body=new URLSearchParams({plate:currentExitPlate,method:$('paymentMethod').value,reference:$('paymentReference').value,quotedFee:String(currentExitFee)});try{const r=await api('/api/payment',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});showResult($('exitResult'),`<b>Barrier OPEN</b><br>Payment: ${esc($('paymentMethod').selectedOptions[0].textContent)}<br>Receipt: ${esc(r.receiptNumber)}<br>VAT included: ${money(r.vatAmount)}`);$('paymentPanel').classList.add('hidden');$('exitForm').reset();$('paymentForm').reset();$('paymentMethod').dispatchEvent(new Event('change'));currentExitPlate='';currentExitFee=0;toast(r.message);refresh()}catch(error){showResult($('exitResult'),error.message||'Payment confirmation failed.',false);if(error.message&&error.message.startsWith('The fee changed')){$('paymentPanel').classList.add('hidden');currentExitFee=0}}finally{button.disabled=false}});
$('cancelPayment').addEventListener('click',()=>{$('paymentPanel').classList.add('hidden');currentExitPlate='';currentExitFee=0;$('exitResult').classList.add('hidden')});
$('searchForm').addEventListener('submit',async e=>{e.preventDefault();try{const plate=encodeURIComponent($('searchPlate').value);const r=await api(`/api/search?plate=${plate}`);showResult($('searchResult'),`<b>Vehicle found</b><br>Allocated slot: <b>${String(r.slotId).padStart(2,'0')}</b><br>Arrival: ${esc(r.arrival)}`)}catch(e){showResult($('searchResult'),e.message||'Vehicle not found.',false)}});
$('ratesForm').addEventListener('submit',async e=>{e.preventDefault();const body=new URLSearchParams(new FormData(e.target));try{const r=await api('/api/rates',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});toast(r.message)}catch(error){toast(error.message||'Could not save rates.')}});
async function loadRates(){try{const rates=await api('/api/rates');for(const [key,value] of Object.entries(rates)){const input=$('ratesForm').elements.namedItem(key);if(input)input.value=value}}catch(error){toast(error.message||'Could not load rates.')}}
$('refreshBtn').addEventListener('click',refresh);loadRates();refresh();setInterval(refresh,3000);
